version: 2
jobs:
  gandalf:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: "echo Hi from Gandalf!"
    branches:
      ignore:
        - gh-pages
  bilbo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: "echo Hi from Bilbo!"
    branches:
      ignore:
        - gh-pages
workflows:
  version: 2
  lotr:
    jobs:
      - gandalf
      - bilbo
      