version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: "echo yarn installing"
      - run: yarn install
      - run: CI=true yarn build
  test:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: "echo unit tests"
      - run: yarn install
      - run: yarn test -- --build
  endofline: 
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: "echo END OF LINE"

workflows:

  version: 2
  build_test_EOL:
    jobs:
      - build
#          branches:
#            ignore:
#              - gh-pages
      - endofline
#          branches:
#            ignore:
#              - gh-pages
      - test:
          requires:
              - endofline
      